version: '3'
services:
  # db:
  #   image: mongo
  #   ports:
  #     - "3099:27017"
  #   deploy:
  #     replicas: 1

  # mq:
  #   image: rabbitmq:3-management
  #   hostname: my-rabbit
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #     - "25676:25676"
  #   labels:
  #     NAME: rabbit13
  #   deploy:
  #     replicas: 1

  auth:
    image: cyberadvance/auth-service
    ports:
      - "3001:3000"
    environment:
      - MONGO_DB_URI=mongodb://3.0.93.150:3099/sch-db
      - AMQP_URL=amqp://18.136.211.198
    deploy:
      replicas: 1

  catalog:
    image: cyberadvance/catalog-service
    ports:
      - "3002:3000"
    environment:
      - MONGO_DB_URI=mongodb://3.0.93.150:3099/sch-db
      - AMQP_URL=amqp://18.136.211.198
    deploy:
      replicas: 1

  acc-sale:
    image: cyberadvance/acc-sale-service
    ports:
      - "3003:3000"
    environment: 
      - MONGO_DB_URI=mongodb://3.0.93.150:3099/acc-db
      - AMQP_URL=amqp://18.136.211.198
    deploy:
      replicas: 1

  